### PR TITLE
Update dockerfile to install freetype

### PR DESCRIPTION
**Pull request by jayschauer**
This fixes issue #4 but I am still having trouble running the docker image, will continue to try to diagnose

### CODE REVIEW

**Comment by GjjvdBurg** [comment]
Thanks for raising this issue and providing the fix @jayschauer! Unfortunately I can't seem to reproduce the issue, but the fix is harmless enough so I'm happy to merge it in. Would you like to keep this open for any other problems you're experiencing with the Dockerfile or shall we merge it in now? (feel free to open an issue for any other problems btw!)

**Comment by jayschauer** [comment]
Actually had another error when I ran the command to reproduce the results. After like 10,000 lines of output, the command exits with error. This is the final output:
```
* installing *source* package 'V8' ...
** package 'V8' successfully unpacked and MD5 sums checked
** using staged installation
Using PKG_CFLAGS=-I/usr/include/v8 -I/usr/include/v8-3.14
Using PKG_LIBS=-lv8 -lv8_libplatform
-----------------------------[ ANTICONF ]-------------------------------
Configuration failed to find the libv8 engine library. Try installing:
 * deb: libv8-dev or libnode-dev (Debian / Ubuntu)
 * rpm: v8-devel (Fedora, EPEL)
 * brew: v8 (OSX)
 * csw: libv8_dev (Solaris)
To use a custom libv8, set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
---------------------------[ ERROR MESSAGE ]----------------------------
<stdin>:1:10: fatal error: v8.h: No such file or directory
compilation terminated.
------------------------------------------------------------------------
ERROR: configuration failed for package 'V8'
* removing '/TCPDBench/execs/R/rlibs/V8'
Error: Failed to install 'unknown package' from URL:
  (converted from warning) installation of package 'V8' had non-zero exit status
Execution halted
[31mNon-zero exit status after installing prophet==0.4[1m[0m
make: *** [Makefile:366: R_venv] Error 1

```

**Comment by jayschauer** [comment]
@GjjvdBurg looks like adding the libv8-dev package to the dockerfile fixed it, the command to reproduce the results ran for much longer. I got this error at the end, so I am going to run it with 2 cores and see what happens:
```
--------------------------------------------------------------------------
There are not enough slots available in the system to satisfy the 4
slots that were requested by the application:

  abed

Either request fewer slots for your application, or make more slots
available for use.

A "slot" is the Open MPI term for an allocatable unit where we can
launch a process.  The number of slots available are defined by the
environment in which Open MPI processes are run:

  1. Hostfile, via "slots=N" clauses (N defaults to number of
     processor cores if not provided)
  2. The --host command line parameter, via a ":N" suffix on the
     hostname (N defaults to 1 if not provided)
  3. Resource manager (e.g., SLURM, PBS/Torque, LSF, etc.)
  4. If none of a hostfile, the --host command line parameter, or an
     RM is present, Open MPI defaults to the number of processor cores

In all the above cases, if you want Open MPI to default to the number
of hardware threads instead of the number of processor cores, use the
--use-hwthread-cpus option.

Alternatively, you can use the --oversubscribe option to ignore the
number of available slots when deciding the number of processes to
launch.
--------------------------------------------------------------------------
```

**Comment by jayschauer** [comment]
The next thing I am going to try is running the benchmark suite with my own dataset, I will update you if I encounter issues

**Comment by jayschauer** [comment]
Woops so I saw that it can take a really long time without a lot of cores, so I only ran the zero changepoint method and that finished successfully

**Comment by GjjvdBurg** [comment]
Thanks for the detailed debugging @jayschauer! I've since been able to reproduce the issue and it looks like your changes solve it! :tada: 

It can indeed take a little while to build the virtual environments and this step does create a lot of output, which can be a bit annoying. The reason we use virtual environments is to ensure that we have the exact same package versions as were used in the original experiments. To (hopefully) make sure these kinds of errors are caught automatically in the future, I'll add a line to the Travis configuration to test building the virtualenvs.

I hope extending the benchmark with your own datasets goes smoothly! Please do let me know if you encounter any further issues, happy to help. 

Thanks again for reporting this issue and providing a fix! :+1:

**Comment by GjjvdBurg** [comment]
> Woops so I saw that it can take a really long time without a lot of cores, so I only ran the zero changepoint method and that finished successfully

Thanks for the confirmation! Yes, while individual experiments are quite fast, it can take a while to run all methods on all datasets with all their hyperparameter variations. Perhaps you don't need to do this for your own experiments though? Otherwise I'd recommend running it on a machine with more cores.

**Comment by jayschauer** [comment]
Yeah I will only be running the methods you showed as the best on my dataset for comparison, and might end up trying a few of my own methods on the various datasets

**Comment by GjjvdBurg** [comment]
Sounds like a plan! :+1:

**Pull request merged**
